cleanup

diff --git a/arch2usb b/arch2usb
--- a/arch2usb
+++ b/arch2usb
@@ -1,15 +1,20 @@
 #!/bin/bash
 
+# DEBUG OPTIONS:
+#set -x # trace complete output
+set -e # stop if one command fails
+set -u # no undefined/empty variables allowed
+set -o pipefail # stop if one pipe fails
 
-# TODO: lot of refactoring ==> split into helper functions 
-
+# INCLUDES
 source $(dirname "$0")/version
 
+# Script that contains the needed variables
+CONFIG_SCRIPT="config.sh"
 
-DEBUG=false
-HELPER=false
+# LOGS
 LOG=true
-LOGFILE=$PWD/build.log
+LOGFILE=$(dirname "$0")/build.log
 
 # ===============================================
 # VARIABLES
@@ -21,46 +26,93 @@ BOOT="/mnt/usb/boot"
 CHROOT="arch-chroot /mnt/usb"
 CHROOTCMD="arch-chroot"
 
-HOSTNAME=flasher
+HOSTNAME=superman
 USER=polar
 ROOTPW="evis32"
 
-# TUI
-TUI="/opt/tui/menu.sh"
+# read packages from file
+PACKAGES=$(tr ' \n' ' ' < $WORK/config/packages.txt)
 
-# BASE PACKAGES
-# TODO: read from package file
-PACKAGES="linux linux-firmware base git base-devel grub efibootmgr polkit vim sudo pv fsarchiver clonezilla partclone partimage libnewt fff ranger tmux nmon"
+#================ LOAD CONFIG ===================#
+function GetVars()
+{
+	# Check for args
+	#if [ ${#SDCARD} == 0 ]; then
+  if [ ${#TAREGT} == 0 ]; then
+		err "No SD Card specified"
+	fi
+  
+	if [ ! -e "${CONFIG_SCRIPT}" ]; then
+		err "Failed to find config script - Exiting..."
+	fi
+
+	BOOT_BLOCK_DEV="${SDCARD}1"
+	ROOTFS_BLOCK_DEV="${SDCARD}2"
+	BASE=$(./${CONFIG_SCRIPT} BASE) || Exit "Failed to parse base directory"
+	DEBOOTSTRAP_TAR=$(./${CONFIG_SCRIPT} DEBOOTSTRAP_TAR) || Exit "Failed to parse debootstrap tar filename"
+	DEBOOTSTRAP=$(./${CONFIG_SCRIPT} DEBOOTSTRAP) || Exit "Failed to parse debootstrap directory"
+	TMP=$(./${CONFIG_SCRIPT} TMP) || Exit "Failed to parse temp directory"
+	MODULES_TMP=$(./${CONFIG_SCRIPT} MODULES_TMP) || Exit "Failed to get modules temp directory"
+	BOOT_TMP=$(./${CONFIG_SCRIPT} BOOT_TMP) || Exit "Failed to get boot files"
+	BOOT_PARTITION_MOUNT=$(./${CONFIG_SCRIPT} BOOT_PARTITION_MOUNT) || Exit "Failed to parse boot partition mount directory"
+	ROOTFS_PARTITION_MOUNT=$(./${CONFIG_SCRIPT} ROOTFS_PARTITION_MOUNT) || Exit "Failed to parse rootfs partition mount directory"
+	BOOT_DISK_LABEL=$(./${CONFIG_SCRIPT} BOOT_DISK_LABEL) || Exit "Failed to parse boot disk label"
+	ROOTFS_DISK_LABEL=$(./${CONFIG_SCRIPT} ROOTFS_DISK_LABEL) || Exit "Failed to parse rootfs disk label"
+	FIRMWARE_DEST=$(./${CONFIG_SCRIPT} FIRMWARE_DEST) || Exit "Failed to get firmware location"
+}
+
+
 
 # ===============================================
 # CLI INTERFACE
 # ===============================================
 
 # OPTIONS (DEFAULT)
-WIPE="NO"
+UNMOUNT="NO"
+FULLWIPE="NO"
+FULLBUILD="NO"
+BASEBUILD="NO"
+UPDATE_TUI="NO"
+UPDATE_CONFIG="NO"
 ENTER_CHROOT="NO"
 TARGET=""
 
+function about() {
+  echo""  
+  echo "┌──────────────────────────────────────────────────┐"
+  echo "│ Arch Live on USB - Image Creator                 │"
+  echo "│ ------------------------------------------------ │"
+  echo "│ Author:   S. Reddy                               │"
+  echo "│ Version:  ${VERSION}                                    │"
+  echo "│ ------------------------------------------------ │"
+  echo "│ Purpose:  Swiss Army Knife with tui for          │"
+  echo "│           arch install, backup & tools           │"
+  echo "└──────────────────────────────────────────────────┘"
+  echo""
+}
 
-function buildimg_usage() {
+function usage() {
     
-  echo "┌──────────────────────────────────────────┐"
-  echo "Usage: $(basename $0) <options>"
+  echo "┌──────────────────────────────────────────────────┐"
+  echo "  USAGE: "
+  echo "    $(basename $0) [options]                   "
+  echo
+  echo "  OPTIONS:"
+  echo "   --fullbuild    build LiveCD on path </mnt/<sdX>"
+  echo "   --basebuild    build only a arch base system "
+  echo "   --fullwipe     wipe USB drive </mnt/<sdX>>"
+  echo "   --chroot       Enter chroot environment"
+  echo
+  echo "   -v, --version  Show $(basename $0) version"
+  echo "   -h, --help     This help dialog"
+  echo "└──────────────────────────────────────────────────┘"
   echo ""
-  echo "Options:"
-  echo "  --target <device-path> :"
-  echo "      Sets target drive /mnt/<sdX>"
-  echo ""
-  echo "  --fullwipe"
-  echo "      Wipe USB drive before building the LiveCD."
-  echo ""
-  echo "  --enter-chroot"
-  echo "      Starts a chroot environment after build."
-  echo ""
-  echo "  --usage"
-  echo "      This help dialog."
-  echo "└──────────────────────────────────────────┘"
-  echo ""
+}
+
+function version()
+{
+  echo "$APP"
+  echo "Version: ${VERSION}"
 }
 
 POSITIONAL=()
@@ -68,28 +120,61 @@ while [[ $# -gt 0 ]]
 do
     key="$1"
     case $key in
-        --target)
+        -f|--fullbuild)
+            FULLBUILD="YES"
+            TARGET="$2"
+            shift
+            shift
+            ;;
+        -b|--base-system)
+            BASEBUILD="YES"
+            TARGET="$2"
+            shift
+            shift
+            ;;
+        --update-tui)
+            UPDATE_TUI="YES"
+            TARGET="$2"
+            shift
+            shift
+            ;;
+        --update-config)
+            UPDATE_CONFIG="YES"
             TARGET="$2"
             shift
             shift
             ;;
         --fullwipe)
-            WIPE="YES"
+            FULLWIPE="YES"
+            TARGET="$2"
             shift
             ;;
-        --enter-chroot)
+        --chroot)
             ENTER_CHROOT="YES"
+            TARGET="$2"
+            shift
             shift
             ;;
-        --usage)
-            buildimg_usage
+        -u|--unmount)
+            UNMOUNT="YES"
+            TARGET="$2"
+            shift
+            shift
+            ;;
+        -v|--version)
+            version
+            exit 0
+            shift
+            ;;         
+        -h|--help)
+            about
             usage
             exit 0
             shift
             ;;
         *)    # unknown option
             POSITIONAL+=("$1") # save it in an array for later
-            echo "Unknown argument: ${POSITIONAL}"
+            echo "ERROR: Unknown argument: ${POSITIONAL}"
             usage
             exit 1
             shift
@@ -99,25 +184,21 @@ done
 set -- "${POSITIONAL[@]}" # restore positional parameters
 
 
+
 # ===============================================
 # CHECKS
 # ===============================================
-# DEBUG OPTIONS:
-# -x = trace complete output
-# -e = if one command fails ==> stop script
-# -u = no undefined/empty variables allowed
-# -o pipefail = stop script if piping to another pipe fails
-[ $DEBUG  == true ] && set -x 
-[ $HELPER == true ] && set -eu && set -o pipefail
-
 # root check 
 [ $(whoami) != root ] && echo "You must be root!" && exit 1
 
 # check for empty target
-[ -z $TARGET ] && echo -e "You must specify a target. Determine the target USB device name with lsblk first!\n" && usage && exit 1
+#[ -z $TARGET ] && echo -e "You must specify a target. Determine the target USB device name with lsblk first!\n" && usage && exit 1
 
 # clean log 
-[ $LOG == true ] && rm $WORK/build.log
+[ $LOG == true ] && [ -f $LOGFILE ] && rm $LOGFILE
+
+
+
 
 # ===============================================
 # FUNCTIONS
@@ -134,6 +215,25 @@ function error()
   [ $LOG == true ] && echo "$1" >> $LOGFILE
   exit 1
 }
+
+function lognl()
+{
+	echo
+	echo "=========================================="
+	echo "STEP: $1"
+	echo "=========================================="
+}
+
+function err()
+{
+	echo
+	echo "=========================================="
+	echo " ERROR:       $1"
+	echo " FROM:        $0"
+	echo "=========================================="
+	exit 1
+}
+
 
 #================ PARTITIONING ===================#
 function partioning()
@@ -158,8 +258,6 @@ function partioning()
   mkfs.ext4 -q ${TARGET}4 && log "Creating ${TARGET}4 fs done!"
 }
 
-
-
 function fullwipe()   # optional
 {
   log "Start full wipe ..."
@@ -167,7 +265,6 @@ function fullwipe()   # optional
   dd if=/dev/zero of=$TARGET status=progress && sync && log "Wiping done!"
   #dd if=/dev/zero of=$TARGET bs=16M status=progress && sync && log "==> Wiping done!"
 }
-
 
 #================ MOUNTING ===================#
 
@@ -183,6 +280,11 @@ function unmounting()
   if mountpoint -q $MNT; then
     log "==> $MNT is still mounted!"
     umount $MNT && log "Unmount $MNT successful!" || error "Failed to unmount $MNT"
+  fi
+
+  if mountpoint -q $MNT; then
+  log "==> $MNT is still mounted!"
+  umount $MNT && log "Unmount $MNT successful!" || error "Failed to unmount $MNT"
   fi
 
   log "==> Unmounting done!" && log ""
@@ -204,7 +306,6 @@ function mounting()
 }
 
 
-
 #================ BASE SYSTEM ===================#
 
 function basesystem()
@@ -214,8 +315,6 @@ function basesystem()
   log "==> Installing base system done!" && log ""
 }
 
-
-
 # Install Yay
 function install_yay()
 {
@@ -224,8 +323,6 @@ function install_yay()
   $CHROOT mkdir -p $PATH && cd $PATH && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
 }
 
-
-
 function fstabgen()
 {
   log "==> Generate a new /etc/fstab using UUIDs as source identifiers"
@@ -233,7 +330,11 @@ function fstabgen()
   log "==> Generating fstab done!" && log ""
 }
 
-#================ CONFIGURE ===================#
+
+
+#==============================================#
+# CONFIGURE
+#==============================================#
 
 function localecfg()
 {
@@ -250,6 +351,9 @@ function localecfg()
   $CHROOT sed -i 's/#de_DE.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/g' /etc/locale.gen
   $CHROOT locale-gen
   $CHROOT echo "LANG=de_DE.UTF-8" > /etc/locale.conf
+
+  $CHROOT ech "KEYMAP=de-latin1" > /etc/vconsole.conf
+
 }
 
 #================ USER-CFG ===================#
@@ -258,7 +362,7 @@ function hostcfg()
 {
   $CHROOT echo ${HOSTNAME} > /etc/hostname && log "==> set hostname to ${HOSTNAME}" 
 
-cat <<EOF > ${MNT}/etc/fstab
+cat <<EOF > ${MNT}/etc/hosts
 127.0.0.1  localhost
 ::1        localhost
 127.0.1.1  ${HOSTNAME}.localdomain  ${HOSTNAME}"
@@ -278,9 +382,9 @@ function bootloader()
 #grub-mkconfig -o /boot/grub/grub.cfg
 #EOF
 
-  $CHROOTCMD ${MNT} grub-install --force --target=i386-pc --recheck ${TARGET}
-  $CHROOTCMD ${MNT} grub-install --force --target=x86_64-efi --efi-directory /boot --recheck --removable
-  $CHROOTCMD ${MNT} grub-mkconfig -o /boot/grub/grub.cfg
+  $CHROOT grub-install --force --target=i386-pc --recheck ${TARGET}
+  $CHROOT grub-install --force --target=x86_64-efi --efi-directory /boot --recheck --removable
+  $CHROOT grub-mkconfig -o /boot/grub/grub.cfg
 }
 
 function newmkinitcpio()
@@ -365,40 +469,50 @@ function rootpwcfg()
 
 
 #================ TUI CONFIG ===================#
+# Autostart does not work:
+# https://serverfault.com/questions/1030047/how-do-i-disable-automatic-login-in-a-debian-live-standard-image/1030050#1030050
+# https://unix.stackexchange.com/questions/669327/gettytty1-serivce-service-is-permanently-restarting-debian-11-live-iso
+
 function copytui()
 {
   log "copy $WORK/tui to ${MNT}/opt"
   cp -rv ${WORK}/tui  /opt
   $CHROOT chown root  /opt/tui/*
   $CHROOT chmod +x    /opt/tui/*
+
+  cp -rv --parents ${WORK}/config/etc/systemd/system/getty\@tty1.service.d/autologin.conf \
+                    ${MNT}/config/etc/systemd/system/getty\@tty1.service.d/autologin.conf       
 }
 
-function autostart()
+function automount()
 {
-log "create tui autostart on getty"
-
-
-cat <<EOF > ${MNT}/etc/fstab
+# automount 
+cat <<EOF > ${MNT}/etc/fstabF
 UUID=${UUID_ROOTFS}  /          ext4  errors=remount-ro  0  1
 UUID=${UUID_DATAFS}  /data      vfat  uid=${IMAGE_USER},gid=${IMAGE_USER}  0  2
 EOF
+}
 
+function tuiautostart()
+{
+log "create tui autostart on getty"
 # file: /etc/systemd/system/getty\@tty1.service.d/override.conf
-cat <<EOF > ${MNT}/etc/systemd/system/getty@tty1.service.d/autologin.conf
+cat <<EOF > ${MNT}/etc/systemd/system/getty\@tty1.service.d/autologin.conf
 [Service]
 ExecStart=
-ExecStart=-/usr/sbin/agetty --autologin root --login-program ${TUI} --noissue --noclear %I $TERM
+ExecStart=-/usr/sbin/agetty --autologin root --login-program /root/tui/menu.sh --mode service --noissue --noclear %I $TERM
 EOF
 
 log "tui getty autostart done!" && log ""
 }
 
-$CHROOT locale-gen de_DE.UTF-8
+
+
 
 # ===========================
-# MAIN
+# MAIN FUNCTIONS
 # ===========================
-img_fullbuild()
+_buildbasesys()
 {
   about
   log "Starting build $(date +"%D %T")"
@@ -413,26 +527,9 @@ img_fullbuild()
   basesystem
   install_yay
   fstabgen
-
-  ### config ###
-  localecfg
-  hostcfg
-
-  # Hint: guess bootloader is here cuz of locales
-  bootloader
-
-  networkcfg
-  networkenable
-
-  rootpwcfg
-  wheelgrpcfg
-
-  #sudocfg #TODO: dont works
-  copytui
-  autostart
 }
 
-img_updatecfg()
+_configure()
 {
   ### fresh mount ###
   unmounting
@@ -442,6 +539,8 @@ img_updatecfg()
   localecfg
   hostcfg
 
+  $CHROOT locale-gen de_DE.UTF-8
+
   networkcfg
   networkenable
 
@@ -450,15 +549,72 @@ img_updatecfg()
 
   #sudocfg #TODO: dont works
   copytui
-  autostart
+  #automount
+  #tuiautostart
+}
+
+fullbuild()
+{
+  _buildbasesys
+  _configure
+}
+
+basebuild()
+{
+  _buildbasesys
+}
+
+updatecfg()
+{
+  _configure
+}
+
+function enter_chroot()
+{ 
+  [ -z ${TARGET} ] && log "You must specify a target!" && exit 1
+  unmounting && mounting ${TARGET}3
+  $CHROOTCMD $MNT
 }
 
 
-if [ "${ENTER_CHROOT}" = "YES" ]
-then
-    log "Enter chroot ..."
-    $CHROOTCMD $MNT
-fi
 
-log "=================================="
-log "IMG BUILD DONE!"
+# ============================================= #
+#  MAIN
+# ============================================= #
+
+if [ ! -z $TARGET ]; then 
+
+  if [ $UNMOUNT == "YES" ]; then
+    umount -A ${TARGET}* && umount ${TARGET}* && lsblk
+  fi
+
+  if [ $FULLWIPE == "YES" ]; then
+    fullwipe
+  fi
+
+  if [ $FULLBUILD == "YES" ]; then
+    log "Build full image ..." && fullbuild
+  fi
+
+  if [ $BASEBUILD == "YES" ]; then
+    log "Build full image ..." && basebuild
+  fi
+
+  if [ $UPDATE_TUI == "YES" ]; then
+      umount ${TARGET}3 && mounting ${TARGET}3 && cp -rv tui /mnt/usb/root/tui
+  fi
+
+  if [ $UPDATE_CONFIG == "YES" ]; then
+      umount ${TARGET}3 && mounting ${TARGET}3 && updatecfg && log "Config is up to date!"
+  fi
+
+  if [ $ENTER_CHROOT == "YES" ]; then
+      enter_chroot
+  fi
+
+  log "=================================="
+  log "DONE!"
+
+else
+  log "You must specify a argument with target!"
+fi
diff --git a/debian2usb b/debian2usb
--- a/debian2usb
+++ b/debian2usb
@@ -9,6 +9,9 @@ set -o pipefail # stop if one pipe fails
 # INCLUDES
 source $(dirname "$0")/version
 
+# Script that contains the needed variables
+CONFIG_SCRIPT="config.sh"
+
 # LOGS
 LOG=true
 LOGFILE=$(dirname "$0")/build.log
@@ -29,6 +32,35 @@ ROOTPW="evis32"
 
 # read packages from file
 PACKAGES=$(tr ' \n' ' ' < $WORK/config/packages.txt)
+
+#================ LOAD CONFIG ===================#
+function GetVars()
+{
+	# Check for args
+	#if [ ${#SDCARD} == 0 ]; then
+  if [ ${#TAREGT} == 0 ]; then
+		err "No SD Card specified"
+	fi
+  
+	if [ ! -e "${CONFIG_SCRIPT}" ]; then
+		err "Failed to find config script - Exiting..."
+	fi
+
+	BOOT_BLOCK_DEV="${SDCARD}1"
+	ROOTFS_BLOCK_DEV="${SDCARD}2"
+	BASE=$(./${CONFIG_SCRIPT} BASE) || Exit "Failed to parse base directory"
+	DEBOOTSTRAP_TAR=$(./${CONFIG_SCRIPT} DEBOOTSTRAP_TAR) || Exit "Failed to parse debootstrap tar filename"
+	DEBOOTSTRAP=$(./${CONFIG_SCRIPT} DEBOOTSTRAP) || Exit "Failed to parse debootstrap directory"
+	TMP=$(./${CONFIG_SCRIPT} TMP) || Exit "Failed to parse temp directory"
+	MODULES_TMP=$(./${CONFIG_SCRIPT} MODULES_TMP) || Exit "Failed to get modules temp directory"
+	BOOT_TMP=$(./${CONFIG_SCRIPT} BOOT_TMP) || Exit "Failed to get boot files"
+	BOOT_PARTITION_MOUNT=$(./${CONFIG_SCRIPT} BOOT_PARTITION_MOUNT) || Exit "Failed to parse boot partition mount directory"
+	ROOTFS_PARTITION_MOUNT=$(./${CONFIG_SCRIPT} ROOTFS_PARTITION_MOUNT) || Exit "Failed to parse rootfs partition mount directory"
+	BOOT_DISK_LABEL=$(./${CONFIG_SCRIPT} BOOT_DISK_LABEL) || Exit "Failed to parse boot disk label"
+	ROOTFS_DISK_LABEL=$(./${CONFIG_SCRIPT} ROOTFS_DISK_LABEL) || Exit "Failed to parse rootfs disk label"
+	FIRMWARE_DEST=$(./${CONFIG_SCRIPT} FIRMWARE_DEST) || Exit "Failed to get firmware location"
+}
+
 
 
 # ===============================================
@@ -71,7 +103,8 @@ function usage() {
   echo "   --fullwipe     wipe USB drive </mnt/<sdX>>"
   echo "   --chroot       Enter chroot environment"
   echo
-  echo "   -h, --help     This help dialog."
+  echo "   -v, --version  Show $(basename $0) version"
+  echo "   -h, --help     This help dialog"
   echo "└──────────────────────────────────────────────────┘"
   echo ""
 }
@@ -87,13 +120,13 @@ while [[ $# -gt 0 ]]
 do
     key="$1"
     case $key in
-        --fullbuild)
+        -f|--fullbuild)
             FULLBUILD="YES"
             TARGET="$2"
             shift
             shift
             ;;
-        --base-system)
+        -b|--base-system)
             BASEBUILD="YES"
             TARGET="$2"
             shift
@@ -122,13 +155,13 @@ do
             shift
             shift
             ;;
-        --unmount)
+        -u|--unmount)
             UNMOUNT="YES"
             TARGET="$2"
             shift
             shift
             ;;
-        --version)
+        -v|--version)
             version
             exit 0
             shift
@@ -182,6 +215,25 @@ function error()
   [ $LOG == true ] && echo "$1" >> $LOGFILE
   exit 1
 }
+
+function lognl()
+{
+	echo
+	echo "=========================================="
+	echo "STEP: $1"
+	echo "=========================================="
+}
+
+function err()
+{
+	echo
+	echo "=========================================="
+	echo " ERROR:       $1"
+	echo " FROM:        $0"
+	echo "=========================================="
+	exit 1
+}
+
 
 #================ PARTITIONING ===================#
 function partioning()
@@ -417,6 +469,10 @@ function rootpwcfg()
 
 
 #================ TUI CONFIG ===================#
+# Autostart does not work:
+# https://serverfault.com/questions/1030047/how-do-i-disable-automatic-login-in-a-debian-live-standard-image/1030050#1030050
+# https://unix.stackexchange.com/questions/669327/gettytty1-serivce-service-is-permanently-restarting-debian-11-live-iso
+
 function copytui()
 {
   log "copy $WORK/tui to ${MNT}/opt"
@@ -424,8 +480,8 @@ function copytui()
   $CHROOT chown root  /opt/tui/*
   $CHROOT chmod +x    /opt/tui/*
 
-  cp -rv --parents ${WORK}/config/etc/systemd/system/getty@tty1.service.d \
-                    /etc/systemd/system/getty@tty1.service.d/autologin.conf      
+  cp -rv --parents ${WORK}/config/etc/systemd/system/getty\@tty1.service.d/autologin.conf \
+                    ${MNT}/config/etc/systemd/system/getty\@tty1.service.d/autologin.conf       
 }
 
 function automount()
@@ -441,7 +497,7 @@ function tuiautostart()
 {
 log "create tui autostart on getty"
 # file: /etc/systemd/system/getty\@tty1.service.d/override.conf
-cat <<EOF > ${MNT}/etc/systemd/system/getty@tty1.service.d/autologin.conf
+cat <<EOF > ${MNT}/etc/systemd/system/getty\@tty1.service.d/autologin.conf
 [Service]
 ExecStart=
 ExecStart=-/usr/sbin/agetty --autologin root --login-program /root/tui/menu.sh --mode service --noissue --noclear %I $TERM
@@ -514,7 +570,8 @@ updatecfg()
 }
 
 function enter_chroot()
-{
+{ 
+  [ -z ${TARGET} ] && log "You must specify a target!" && exit 1
   unmounting && mounting ${TARGET}3
   $CHROOTCMD $MNT
 }
@@ -544,11 +601,11 @@ if [ ! -z $TARGET ]; then
   fi
 
   if [ $UPDATE_TUI == "YES" ]; then
-      mounting $TARGET && cp -rv tui /mnt/usb/root/tui
+      umount ${TARGET}3 && mounting ${TARGET}3 && cp -rv tui /mnt/usb/root/tui
   fi
 
   if [ $UPDATE_CONFIG == "YES" ]; then
-      mounting $TARGET && updatecfg && log "Config is up to date!"
+      umount ${TARGET}3 && mounting ${TARGET}3 && updatecfg && log "Config is up to date!"
   fi
 
   if [ $ENTER_CHROOT == "YES" ]; then
