optimizing....
still a lot of work to do

diff --git a/arch2usb b/arch2usb
--- a/arch2usb
+++ b/arch2usb
@@ -12,15 +12,16 @@ LOG=true
 # ===============================================
 WORK="$(dirname $(readlink -f $0))"
 LOGFILE="$WORK/build.log"
-source $WORK/version
+source ${WORK}/version
 
-MNT="/mnt/usb"
+MNT="/mnt/archrootfs"
 BOOT="/mnt/usb/boot"
+ROOTFS="$MNT"
 
 PACKAGES=$(tr ' \n' ' ' < $WORK/config/packages.txt)
 
-CHROOT="arch-chroot /mnt/usb"
-CHROOTCMD="arch-chroot"
+CHROOT="arch-chroot ${ROOTFS}"
+CHROOTCMD="arch-chroot ${MNT}"
 
 HOSTNAME=superman
 USER=polar
@@ -46,7 +47,7 @@ function about() {
   echo "│ Arch Live on USB - Image Creator                 │"
   echo "│ ------------------------------------------------ │"
   echo "│ Author:   S. Reddy                               │"
-  echo "│ Version:  ${VERSION}                                    │"
+  echo "│ Version:  ${ARCH_VERSION}                                    │"
   echo "│ ------------------------------------------------ │"
   echo "│ Purpose:  Swiss Army Knife with tui for          │"
   echo "│           arch install, backup & tools           │"
@@ -200,30 +201,36 @@ function err()
 
 #================ PARTITIONING ===================#
 function partioning()
-{  
-  log "Create 10MB BIOS, 500MB EFI, 3GB for Linux fs and remaining space for image files"
+{ 
+  lognl "Partioning ..." 
+  #Create 10MB BIOS, 500MB EFI, 3GB for Linux fs and remaining space for image files
   sgdisk -Z ${TARGET}
-  sgdisk -o -n 1:0:+10M -t 1:EF02 -n 2:0:+500M -t 2:EF00 -n 3:0:+3G -t 3:8300 -n 4:0:0 -t 4:8300 $TARGET
+  sgdisk -o -n 1:0:+10M   -t 1:EF02 \
+  #          -n 2:0:+500M  -t 2:EF00 \
+            -n 2:0:+3G    -t 2:8300 \
+            -n 3:0:0      -t 3:8300 \
+            ${TARGET}
 
+  #wipefs -a ${TARGET}2
   wipefs -a ${TARGET}2
   wipefs -a ${TARGET}3
-  wipefs -a ${TARGET}4
 
+  lognl "Formating ..."
   # Hint: Do not format the /dev/sdX1 block. This is the BIOS/MBR parition."
 
   # Format the 500MB EFI system partition with a FAT32 filesystem:
-  mkfs.fat -F32 ${TARGET}2 && log "Creating ${TARGET}2 fs done!"
+  #mkfs.fat -F32 ${TARGET}2 && log "Creating ${TARGET}2 fs done!"
 
   # Format the Linux partition with an ext4 filesystem:
-  mkfs.ext4 -q ${TARGET}3 && log "Creating ${TARGET}3 fs done!"
+  mkfs.ext4 -q ${TARGET}2 && log "Creating ${TARGET}2 fs done!"
 
   # Format the data partition with an exfat/ntfs filesystem:
-  mkfs.ext4 -q ${TARGET}4 && log "Creating ${TARGET}4 fs done!"
+  mkfs.exfat -q ${TARGET}3 && log "Creating ${TARGET}3 fs done!"
 }
 
 function fullwipe()   # optional
 {
-  log "Start full wipe ..."
+  lognl "Full wipe ..."
   log "This may take long time depending on disk size (1 hour+)"
   dd if=/dev/zero of=$TARGET status=progress && sync && log "Wiping done!"
   #dd if=/dev/zero of=$TARGET bs=16M status=progress && sync && log "==> Wiping done!"
@@ -233,39 +240,21 @@ function fullwipe()   # optional
 
 function unmounting()
 {
-  log "==> Unmount first ..."
-
-  if mountpoint -q $BOOT; then
-    log "==> $BOOT is still mounted!"
-    umount $BOOT && log "Unmount $BOOT sucessfull!" || error "Failed to unmount $BOOT" 
-  fi
-  
-  if mountpoint -q $MNT; then
-    log "==> $MNT is still mounted!"
-    umount $MNT && log "Unmount $MNT successful!" || error "Failed to unmount $MNT"
-  fi
-
-  if mountpoint -q $MNT; then
-  log "==> $MNT is still mounted!"
-  umount $MNT && log "Unmount $MNT successful!" || error "Failed to unmount $MNT"
-  fi
-
-  log "==> Unmounting done!" && log ""
+  lognl "Unmount ..."
+  mountpoint -q $MNT && umount -A ${TARGET}* || log "No device mounted!"
 }
 
 function mounting()
 {
-  log "==> Start mounting ..."
+  lognl "Mounting ..."
   
-  log "==> Mount the ext4 formatted partition as the root filesystem"
   mkdir -p "$MNT" && log "Creating mountpoint $MNT done!"
-  mount ${TARGET}3 $MNT && log "Mounting ${TARGET}3 on $MNT done!" || error "Mounting ${TARGET}3 on $MNT failed!"
+  mount ${TARGET}2 $MNT && log "Mounting ${TARGET}2 on $MNT done!" || error "Mounting ${TARGET}3 on $MNT failed!"
 
-  log "==> Mount the FAT32 formatted EFI partition to /boot"
-  mkdir -p "$BOOT" && log "Creating mountpoint $BOOT done!"
-  mount ${TARGET}2 $BOOT && log "Mounting ${TARGET}2 on $BOOT done!" || error "Mounting ${TARGET}3 on $BOOT failed! ==> Hint: Reboot if mount fails due to unknow filesystem type »vfat«!"
+  #log "==> Mount the FAT32 formatted EFI partition to /boot"
+  #mkdir -p "$BOOT" && log "Creating mountpoint $BOOT done!"
+  #mount ${TARGET}2 $BOOT && log "Mounting ${TARGET}2 on $BOOT done!" || error "Mounting ${TARGET}3 on $BOOT failed! ==> Hint: Reboot if mount fails due to unknow filesystem type »vfat«!"
 
-  log "==> Mounting done!" && log ""
 }
 
 
@@ -273,9 +262,10 @@ function mounting()
 
 function basesystem()
 {
-  log "==> Download and install the Arch Linux base packages using pacstrap."
+  lognl "Install base system ..."
+  # download and install the Arch Linux base packages using pacstrap.
   pacstrap $MNT $PACKAGES && \
-  log "==> Installing base system done!" && log ""
+  log "==> base system installed!" && log ""
 }
 
 # Install Yay
diff --git a/debian2usb b/debian2usb
--- a/debian2usb
+++ b/debian2usb
@@ -12,24 +12,23 @@ LOG=true
 # ===============================================
 WORK="$(dirname $(readlink -f $0))"
 LOGFILE="$WORK/build.log"
-source $WORK/version
+source ${WORK}/version
 
 MNT="/mnt/rootfs"
 ROOTFS="$MNT"
-BOOT="$MNT/boot"
+CHROOT="chroot $MNT"
 
-PACKAGES=$(tr ' \n' ' ' < $WORK/config/packages.txt)
-PACKAGES=$(tr ' \n' ' ' < $WORK/config/packages-debian.txt)
-
-CHROOT="arch-chroot /mnt/usb"
-CHROOTCMD="arch-chroot"
+PACKAGES=$(tr ' \n' ' ' < $WORK/config/packages-ubuntu.txt)
 
 HOSTNAME=superman
 USER=polar
 ROOTPW="evis32"
 
-STRAPCMD="pacstrap $MNT $PACKAGES" 
-STRAPCMD="debootstrap --include '$PACKAGES' --arch amd64 bullseye ${MNT}"
+#STRAPCMD="pacstrap $MNT $PACKAGES" 
+#STRAPCMD="debootstrap --include '$PACKAGES' --arch amd64 bullseye ${MNT}"
+
+REPO_URL="http://de.archive.ubuntu.com/ubuntu"
+REPO_URL_ARM="http://ports.ubuntu.com" #"http://ports.ubuntu.com/ubuntu-ports"
 
 # ===============================================
 # CLI INTERFACE
@@ -43,6 +42,7 @@ BASEBUILD="NO"
 UPDATE_TUI="NO"
 UPDATE_CONFIG="NO"
 ENTER_CHROOT="NO"
+NOPART="NO"
 TARGET=""
 
 function about() 
@@ -68,8 +68,9 @@ function usage()
   echo "    $(basename $0) [options] [target]               "
   echo
   echo "  OPTIONS:"
-  echo "   -f, --fullbuild    build to target </mnt/<sdX>"
-  echo "   -b, --basebuild    build to target </mnt/<sdX>"
+  echo "   -f, --fullbuild    build complete system"
+  echo "   -b, --basebuild    build only base system"
+  echo "   -n, --nopart       build on existing partitions"
   echo "   -w, --fullwipe     wipe USB drive  </mnt/<sdX>"
   echo "   -c, --chroot       enter chroot    </mnt/<sdX>"
   echo
@@ -78,6 +79,9 @@ function usage()
   echo
   echo "   -v, --version      Show $(basename $0) version"
   echo "   -h, --help         This help dialog"
+  echo 
+  echo "  EXAMPLE:"
+  echo "   $(basename $0) --fullbild </mnt/sdX>"
   echo "└──────────────────────────────────────────────────┘"
   echo ""
 }
@@ -100,6 +104,12 @@ do
             ;;
         -b|--base-system)
             BASEBUILD="YES"
+            TARGET="$2"
+            shift
+            shift
+            ;;
+        -n|--nopart)
+            NOPART="YES"
             TARGET="$2"
             shift
             shift
@@ -262,34 +272,61 @@ function fullwipe()   # optional
 }
 
 #================ BASE SYSTEM ===================#
-
 function basesystem()
 {
   lognl "Install base system ..."
-  $STRAPCMD && log "==> Base system installed!" && log ""
+  
+  # use debootstrap from from arch linux host !
+  debootstrap --no-check-gpg --arch=amd64 focal ${ROOTFS} http://de.archive.ubuntu.com/ubuntu    
 }
-
 
 #==============================================#
 # CONFIGURE
 #==============================================#
-
-function config_full()
+function copy_mtab()
 {
   # currently mounted filesystems
   cp -v /etc/mtab ${ROOTFS}/etc/mtab
+}
 
-  # mount virtual filesystems
+mount_dev_proc_sys()
+{
+  lognl "Mount /dev /proc /sys"
+    # mount virtual filesystems
   # arch does this automatically
   mount -o bind /dev      ${MNT}/dev
   mount -o bind /dev/pts  ${MNT}/dev/pts
   mount -o bind /proc     ${MNT}/proc
   mount -o bind /sys      ${MNT}/sys
-
-  #chroot ${MNT} apt install arch-install-scripts
-
-  fstabgen
 }
+
+function editpkglist()
+{
+  # default: deb http://de.archive.ubuntu.com/ubuntu focal main
+  REPO=focal
+  REPO_URL="http://de.archive.ubuntu.com/ubuntu"
+  REPO_COMPONENTS="main universe multiverse"
+  echo "" > "${ROOTFS}/etc/apt/sources.list"
+  echo "deb ${REPO_URL} ${REPO} ${REPO_COMPONENTS}" >> "${ROOTFS_PATH}/etc/apt/sources.list"
+}
+
+function update()
+{
+  chroot ${ROOTFS} apt update
+  chroot ${ROOTFS} apt -y install software-properties-common
+  
+  # software-properties-common
+  # no need to add/remove repositories (such as PPAs) manually by editing /etc/apt/sources.list 
+  #   dpkg -L software-properties-common | grep 'bin/'
+  #   /usr/bin/add-apt-repository
+  #   /usr/bin/apt-add-repository
+}
+
+function installpkg()
+{
+  chroot ${MNT} apt install -y $PACKAGES
+}
+
 
 function fstabgen()
 {
@@ -304,14 +341,13 @@ function fstabgen()
 function localecfg()
 {
   lognl "Configure time ..."
-  chroot ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime && log "==> Set timezone !" || err "Failed to set timezone!"
-  chroot hwclock --systohc && log "==> Generate /etc/adjtime (hwclock)" || err "Failed to set /etc/adjtime!"
-
+  chroot ${ROOTFS} ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime && log "==> Set timezone !" || err "Failed to set timezone!"
+  chroot ${ROOTFS} hwclock --systohc && log "==> Generate /etc/adjtime (hwclock)" || err "Failed to set /etc/adjtime!"
+  
   lognl "Configure language & keyboard ..."
-  $CHROOT sed -i 's/#de_DE.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/g' /etc/locale.gen
-  chroot locale-gen
-  chroot echo "LANG=de_DE.UTF-8" > /etc/locale.conf
-  chroot echo "KEYMAP=de-latin1" > /etc/vconsole.conf
+  chroot ${ROOTFS} locale-gen de_DE.UTF-8
+
+  #chroot echo "KEYMAP=de-latin1" > /etc/vconsole.conf
 }
 
 #================ USER-CFG ===================#
@@ -319,7 +355,7 @@ function localecfg()
 function hostcfg()
 {
   lognl "Configure hostname & hosts ..."
-  chroot echo ${HOSTNAME} > /etc/hostname && log "==> set hostname to ${HOSTNAME}" || err "Failed to set hostname!"
+  echo ${HOSTNAME} > ${ROOTFS}/etc/hostname && log "==> Set hostname to ${HOSTNAME}" || err "Failed to set hostname!"
 
 cat <<EOF > ${ROOTFS}/etc/hosts
 127.0.0.1  localhost
@@ -333,16 +369,9 @@ EOF
 
 #================ BOOTLAODER ===================#
 
-function arch_bootloader()
+function efi_bootloader()
 {
-  lognl "Install Bootloader"
-#cat << EOF | $CHROOT
-#grub-install --target=i386-pc --recheck ${TARGET} && \
-#grub-install --target=x86_64-efi --efi-directory /boot --recheck --removable && \
-#grub-mkconfig -o /boot/grub/grub.cfg
-#EOF
-
-  $CHROOT grub-install --force --target=i386-pc --recheck ${TARGET}
+  #$CHROOT grub-install --force --target=i386-pc --recheck ${TARGET}
   $CHROOT grub-install --force --target=x86_64-efi --efi-directory /boot --recheck --removable
   $CHROOT grub-mkconfig -o /boot/grub/grub.cfg
 }
@@ -357,7 +386,7 @@ function bootloader()
 
 function newmkinitcpio()
 {
- echo "TODO"
+  echo "TODO"
 }
 
 #================ END::BOOTLAODER ===================#
@@ -523,22 +552,6 @@ _configure()
   #tuiautostart
 }
 
-fullbuild()
-{
-  _buildbasesys
-  _configure
-}
-
-basebuild()
-{
-  _buildbasesys
-}
-
-updatecfg()
-{
-  _configure
-}
-
 
 
 # ============================================= #
@@ -548,12 +561,27 @@ function fullbuild()
 { 
   [ -z ${TARGET} ] && log "You must specify a target!" && exit 1
   _buildbasesys
-
-
-
+  _configure
 }
 
+basebuild()
+{
+  [ -z ${TARGET} ] && log "You must specify a target!" && exit 1
+  _buildbasesys
+}
 
+updatebuild()
+{
+  [ -z ${TARGET} ] && log "You must specify a target!" && exit 1
+
+  about
+  log "Starting build $(date +"%D %T")" && log ""
+  sleep 2
+
+  basesystem
+  config_full
+  bootloader
+}
 
 
 function update_tui()
@@ -567,13 +595,13 @@ function update_config()
 { 
   [ -z ${TARGET} ] && log "You must specify a target!" && exit 1
   unmounting && mounting ${TARGET}2 && \
-  updatecfg && log "Config is up to date!" || err "Failed to update config!"
+  _configure && log "Config is up to date!" || err "Failed to update config!"
 }
 
 function enter_chroot()
 { 
   [ -z ${TARGET} ] && log "You must specify a target!" && usage && exit 1
-  unmounting && mounting && chroot $ROOTFS
+  unmounting && mounting && chroot $ROOTFS /bin/bash
 }
 
 
@@ -602,16 +630,20 @@ if [ ! -z $TARGET ]; then
     basebuild
   fi
 
+  if [ $NOPART == "YES" ]; then
+    updatebuild
+  fi
+
   if [ $UPDATE_TUI == "YES" ]; then
     update_tui
   fi
 
   if [ $UPDATE_CONFIG == "YES" ]; then
-     update_config 
+    update_config 
   fi
 
   if [ $ENTER_CHROOT == "YES" ]; then
-      enter_chroot
+    enter_chroot
   fi
 
   log "=================================="
